version: '3.0'
services:
  node:
    container_name: node
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://db:27017
    restart: on-failure

  db:
    container_name: db
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./db/initdb.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - 27017:27017

networks:
  gpt-simulation: